# Testing docker image to run QGIS via SSH
# 20200514 - CC BY-SA - Miguel Sevilla-Callejo

FROM ubuntu:focal

LABEL Name=qgisdev_docker Version=0.1
LABEL maintainer "Miguel Sevilla-Callejo <msevilla00@gmail.com>"

ENV DEBIAN_FRONTEND noninteractive

# default user: `qgis`
#ENV USER="qgis"

# add necessary packages
RUN apt-get update \
  && apt-get install -y \
    curl \
    gpg \
    keyboard-configuration \
    nano \
    software-properties-common \
    ssh \
    unzip \
    wget \
    xvfb

#ENV LANG en_US.UTF-8
#ENV LANGUAGE en_US.UTF-8
#ENV LC_ALL en_US.UTF-8

# ADD QGIS to the system ######################################################## 

# Add QGIS dev repository
#RUN echo "deb https://qgis.org/ubuntu-nightly focal main" > /etc/apt/sources.list.d/qgis-dev.list

# Add QGIS Latest release repository
#RUN echo -e "deb http://qgis.org/ubuntu focal main" > /etc/apt/sources.list.d/qgis-latest.list

# Add QGIS repository file to apt sources list directory
ADD qgis-dev.list /etc/apt/sources.list.d/

# Add QGIS repository
#RUN apt-key adv --keyserver keyserver.ubuntu.com --recv-key 51F523511C7028C3
RUN wget -qO - https://qgis.org/downloads/qgis-2020.gpg.key | gpg --no-default-keyring --keyring gnupg-ring:/etc/apt/trusted.gpg.d/qgis-archive.gpg --import
RUN chmod a+r /etc/apt/trusted.gpg.d/qgis-archive.gpg
RUN apt-get update
RUN apt-get install -y qgis qgis-plugin-grass 

# Uncomment if you want to install QGIS server
#RUN apt-get install qgis-server

# Set up SSH service to use X outside of the container
RUN sed -i 's/\#X11UseLocalhost yes/X11UseLocalhost no/g' /etc/ssh/sshd_config

# Maintain the system clean to slim it / NOT NECESSARY
#RUN apt-get clean && apt-get autoclean && apt-get autoremove

# Create new user and add password to it
#RUN useradd --create-home --shell /bin/bash ${USER}
RUN useradd --create-home --shell /bin/bash qgis
RUN echo -n 'qgis:qgis2020' | chpasswd

# Create a data folder withing the new created user home
RUN mkdir -p /home/qgis/data \
    && chown 777 /home/qgis/data
VOLUME home/qgis/data

# Run container with above user and home user
#USER ${USER}
#WORKDIR /home/${USER}/data

# Start SSH service --> DO NOT WORK --> move to supervisor
#RUN service ssh start
#RUN /usr/bin/sshd -D

# Add supervisor ##########################################################

# create directory for child images to store configuration in
RUN apt-get -y install supervisor && \
  mkdir -p /var/log/supervisor

    # Add supervisor service configuration script
COPY ./supervisor/ /etc/supervisor

    # Run supervisor
CMD ["/usr/bin/supervisord", "-c", "/etc/supervisor/supervisord.conf"]


###########################################################################
# To BUILD IMAGE with this code run:
# `docker build -t msevilla00/qgis_dev:v1c -f dev.dockerfile .`

# To RUN QGIS from container:
# xhost + 
# & docker run --rm -it --name qgisdev \
#   -v /datafolder:/home/qgis/data \
#   -v /tmp/.X11-unix:/tmp/.X11-unix \
#   -e DISPLAY=unix$DISPLAY \
#   msevilla00/qgis_dev qgis